### ISSUE TITLE
Which version of pixi is required?!?

### ISSUE THREAD

**Issue by pate313373** [davidfig/pixi-viewport#124]
Hi,

I'd like to use this awesome addon, but have no clue how. :(
I'm using https://pixijs.download/v4.8.6/pixi.min.js, but obviously it is not compatible. - Any help appreciated.

Please see my test code below.

BR
pate

[test_canvas.txt](https://github.com/davidfig/pixi-viewport/files/2959166/test_canvas.txt)

**Comment by davidfig** [comment]
pixi-viewport works with v4+ and v5. Your code is close, but needs a few tweaks:

```html
<title>Test Canvas</title>
<script src="https://pixijs.download/v4.8.6/pixi.min.js"></script>
<script src="https://github.com/davidfig/pixi-viewport/releases/download/3.4.1/pixi-viewport.min.js"></script>
<script>
window.onload = function ()
{
	var app = new PIXI.Application();
	document.body.appendChild(app.view);

	// create viewport
	var viewport = new PIXI.extras.Viewport({
		screenWidth: window.innerWidth,
		screenHeight: window.innerHeight,
		worldWidth: 1000,
		worldHeight: 1000,

		interaction: app.renderer.plugins.interaction // the interaction module is important for wheel() to work properly when renderer.view is placed or scaled
	});

	// add the viewport to the stage
	app.stage.addChild(viewport);

	// activate plugins
	viewport
		.drag()
		.pinch()
		.wheel()
		.decelerate();

	// add a red box
	var sprite = viewport.addChild(new PIXI.Sprite(PIXI.Texture.WHITE));
	sprite.tint = 0xff0000;
	sprite.width = sprite.height = 100
	sprite.position.set(100, 100);
}
</script>
```

I'd recommend learning how to package the code (see browserify or budo) so you can get the newest libraries for pixi and pixi-viewport. 

Good luck!

David

**Comment by pate313373** [comment]
Thank you David! Working great now! :)

Just to understand things right, your example in the readme tells
`var PIXI = require('pixi.js');
var Viewport = require('pixi-viewport');`

But PixiJS docu says I should rather use:
`import * as PIXI from 'pixi.js'`

When to use these options at all? If I write a NodeJS script using Pixi and pixi-viewport, I can only run it in the console, right? Could you give me a hint how to use pixi-viewport with NodeJS and publish the result in a browser?

**Comment by davidfig** [comment]
require vs. import is a complicated issue for nodejs and browsers. You should read through this conversation: https://stackoverflow.com/questions/46677752/the-difference-between-requirex-and-import-x/46677972

I like using require because I use budo/browserify as my development stack. pixi.js uses the import syntax because they use rollup. Both gets the same result: namely, a compiled javascript package that includes external libraries (like pixi.js and pixi-viewport).

node.js isn't used to develop browser code. It's used for developing server-side code (I know, super confusing). For example, I use node.js for the backend of my games.

For browser code (i.e., javascript that will run in the browser), I use browserify (or rollup or webpack) to bundle the app together with its libraries. Think of nodejs as your backend code, and your bundler as your frontend code.

Check out: https://rollupjs.org/guide/en#overview For an overview of how to use rollup to create something that can be deployed to a browser. Rollup is a more modern solution, so you should probably start there.

Javascript is confusing when it comes to figuring out the build stack, but once you get there it's a great platform.

**Comment by pate313373** [comment]
Well, I'm already working with node-red, so I'm used to server-side JS for backends.
Ok, guess I got the point in regard of require and import.

There is just a very last thing that's confusing me:
If you create a new project, you create a new folder, npm i pixi.js and npm i pixi-viewport, so you have a project folder with all dependencies, but what now? pixi.js just offers export and pixi-viewport just offers module.exports, so how can I bundle these two libraries, using two different technologies?

Thank you for the great support! :)

**Comment by davidfig** [comment]
I hadn't seen node-red before. Looks cool.

This is where your bundler comes in. When you npm i, you're installing the external libraries to the node_modules/ directory. The bundler then takes those libraries and bundles them into a single javascript file. I expect node-red provides similar functionality as a bundler. Here's my flow for testing stuff:

1. create new directory and npm i libraries
2. create an index.js file that has
```js
const pixi = require('pixi.js')
const viewport = require('pixi-viewport')

window.onload = () => {
 // insert code here, e.g., the code between the <script> tags above
}
```
3. npm i -g budo (you may need to sudo if you're not on windows; this installs budo, which is a quick way of testing bundled code in the browser)
4. run budo (just type budo from the command line)
5. Open your browser to localhost:9966 and you should see the demo code running

You can, of course, do much more by providing your own index.html, and separating stuff into directories. You'll also need more tools to bundle it for release, bu this should get you started.

**Comment by pate313373** [comment]
I can highly recommend to have a closer look at node-red, database nodes, REST nodes (integrated), and especially node-dashboard. :) 👍 
node-red requires bundeled nodes already, so it's not really a bundler, but more a message router.

I see, thank you for the detailed explaination! I'll try it tomorrow. :)
Btw, is there any chance to get the source of https://davidfig.github.io/pixi-viewport/?

**Comment by davidfig** [comment]
I'll take a look at the node-red library. 

The full source of the demo is available in the docs/ directory here: https://github.com/davidfig/pixi-viewport/tree/master/docs

The unbundled code is in the code.js file and its imports.

**Comment by pate313373** [comment]
Thank you so much for your help David! :)
Let me know if I can help with node-red!

BR pate
