### ISSUE TITLE
Setting options.pauseOnBlur has no effect

### ISSUE THREAD

**Issue by qwertysam** [davidfig/pixi-viewport#14]
Upon constructing the viewport, the option options.pauseOnBlur doesn't seem to do anything. Especially noticable with the follow, decelerate, and snap plugins. When switching to a different tab, I expect the plugins to still be constantly running when I set options.pauseOnBlur to false. However, the actual result is that pixi-viewport plugins halt until I switch back to the original tab.

**Comment by davidfig** [comment]
Where are you testing this? Are you using viewport.start() or manually updating the loop?

**Comment by qwertysam** [comment]
using viewport.start()

Full code is here
```
var options = {
    pauseOnBlur: true,
    screenWidth: w,
    screenHeight: h,
    worldWidth: w,
    worldHeight: h,
};

var viewport = new Viewport(game.stage, options);

var clampOptions = {
    minWidth: 1,
    minHeight: minHeight,
    maxWidth: 1000 * w,
    maxHeight: maxHeight
};

viewport
    .drag()
    .wheel()
    .pinch({
        percent: 4.5
    })
    .clampZoom(clampOptions)
    .decelerate()
    .start();
```

**Comment by davidfig** [comment]
So when pauseOnBlur = false, then the viewport still pauses when focus is lost?

**Comment by qwertysam** [comment]
Correct. I can confirm that pauseOnBlur acts appropriately when manually updating the viewport via
```
game.ticker.add(function () {
    viewport.update();
}
```

**Comment by davidfig** [comment]
Hmm...strange. 

Have you tried it with overlay windows or Chrome's devtool instead of tabs? options.pauseOnBlur is triggered only when using the viewport's built in loop through viewport.start(). It should have no effect if you manually call viewport.update. I checked PIXI.Ticker, and it does not have a blur event handler.

**Comment by qwertysam** [comment]
My apologies, I retested the viewport. Regardless of the value of the option `pauseOnBlur` ...
- When starting using `viewport.start()` the viewport always pauses upon blurring
- When using `viewport.update()` in a PIXI.ticker loop, the viewport never pauses upon blurring

**Comment by davidfig** [comment]
Ugh. I still can't replicate this bug. 

Can you try the demo: https://davidfig.github.io/pixi-viewport/ It's currently set with pauseOnBlur: false so it should not pause when blurring. 

The PIXI.ticker.loop makes sense since the pauseOnBlur only works when using yy-loop's start() command. It's ignored if you use your own loop.

**Comment by qwertysam** [comment]
Tried the demo, same results: https://youtu.be/BFKZDqoMZSo

**Comment by davidfig** [comment]
Ok. Did a bit of research. I remember I spent many hours on this when I was first worked on my loop API (mostly around whether to use blur/focus or page visibility).

The tab issue is related to battery life (from [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API)]: 

* Window.requestAnimationFrame() calls are paused in most browsers when running in background tabs or hidden <iframe>s in order to improve performance and battery life. 

The pauseOnBlur works when you switch applications, but not when switching tabs. Not sure how PIXI.ticker does it since they should have the same limitation when switching tabs.
