### ISSUE TITLE
contextmenu is blocked on the whole page

### ISSUE THREAD

**Issue by MRVDH** [davidfig/pixi-viewport#146]
Thanks for the documentation update and the migration guide! Everything seems to work apart from this small bug.

No matter where I click on the page (aka even outside the canvas) the contextmenu (right click) is blocked.

*playground link to see for yourself:* https://www.pixiplayground.com/#/edit/f2YE16DCA~l_SdCqb3UEu

Image of where it's being blocked according to Chrome (this is the minified latest release):

![image](https://user-images.githubusercontent.com/6686385/60330489-d63b5b80-9992-11e9-8522-698e6bb7302e.png)

**Comment by davidfig** [comment]
Yup. I did that to enable right-click drag on the viewport. I'll add an option to disable that behavior. For now, if you set options.divWheel = your canvas element, then it will only block the right-click on the canvas.

**Comment by davidfig** [comment]
v4.0.0-beta.3 has options.noOnContextMenu. Set to true to remove the oncontextmenu call.

**Comment by MRVDH** [comment]
Great! Could you add it to the release page? 😄

**Comment by davidfig** [comment]
Done. I really need to remember that step....

**Comment by MRVDH** [comment]
Works well, thanks for the quick implementation!

**Comment by soylomass** [comment]
I just found this after finding out that my right click didn't work on the whole site. After using Chrome global search I found that line of code and realised the problem.

I'd recommend adding divWheel parameter to the example code in the main page and every documentation, commenting that the default is body and it will disable right click for said element, otherwise some people may never find the cause of the problem.

Thanks

**Comment by davidfig** [comment]
I agree. I'm going to make a breaking change and disable this by default. I think it causes too much confusion. I'll leave it in as an option and add a couple of notes to the drag plugin so people can enable it if needed for right click. Published as v4.2. Thanks for the feedback!
