### ISSUE TITLE
Scaling grid

### ISSUE THREAD

**Issue by ptsans** [davidfig/pixi-viewport#160]
Hi, help me understand.
Why does the grid behave this way when scaling? 
https://codepen.io/Pakos/full/yLBqMdx
Can this be fixed?

**Comment by davidfig** [comment]
Are you talking about zooming all the way out? If so, you're running into pixel-size issues. A better way to implement a grid is to place a pixi.graphics() over the viewport (not in the viewport). Then you manually draw the grid lines at size 1 based on viewport's scale and position. That way the always have a width of 1 instead of subpixel sizes, and as a bonus your grid can support any world size.

**Comment by ptsans** [comment]
so, do I have to redraw the grid manually for each "drag" and "wheel" event?  I think for a large grid, this will affect performance

**Comment by davidfig** [comment]
Yes, that's the way I did it. When I implemented It, there was no impact on performance (probably since you're just drawing a bunch of vertical and horizontal lines). I updated it every time the viewport was dirty, but probably could have updated it every frame without any problems.

**Comment by ptsans** [comment]
I'll try that. Thanks for replies.
