### ISSUE TITLE
`ensureVisible()` does not view entire bounding box

### ISSUE THREAD

**Issue by jasonsturges** [davidfig/pixi-viewport#197]
Relates to #163 - `ensureVisible()` sometimes positions, but does not scale to width and height.

Codepen to demonstrate the issue: https://codepen.io/jasonsturges/pen/BayMWxm

Calling this at position 0, 0 with 1000x1000 width and height:

```
viewport.ensureVisible(0, 0, 1000, 1000);
```

Unless I'm mistaken, I'd think the upper left of the viewport would be at position 0, 0, and ensure 1000 width and height - a best fit of the bounding box into the view.

Or is that not the way it works?

**Comment by davidfig** [comment]
Originally, `ensureVisible` did not scale the viewport, it only moves the viewport (as much as possible) to show the content. 

Since this is a requested feature, I just released 4.7.0 that includes an option to change the scale: `ensureVisible(x, y, width, height, resizeToFit: boolean)`. To use it, just call add a true as the last parameter: `ensureVisible(x, y, width, height, true)` and it'll internally call `viewport.fit(width, height)` to resize the viewport as needed.

**Comment by jasonsturges** [comment]
So awesome - thanks!
