### ISSUE TITLE
Specify percent in `SnapZoomOptions`

### ISSUE THREAD

**Issue by jasonsturges** [davidfig/pixi-viewport#213]
Having some trouble matching zoom systems in my solution.

Without animation, there's:
- `zoom`: Relative change by pixels
- `zoomPercent`: Relative change by percent
- `setZoom()`: Set scale to percent

While that's very flexible, for animation using `snapZoom`, the `SnapZoomOptions` specify a width and height.  

How do I derive the equivalent percent for `snapZoom`?  Would width be `worldWidth`, `screenWidth`, or `getLocalBounds()` multiplied by the zoom percent?

Seem like half of screen width `screenWidth * 0.5` gives a 200% zoom `viewport.scale.x = 2`.

After zooming using `snapZoom`, I can't seem to understand what the resultant zoom percent would have been compared to the viewport scale.

Definitely understand if you don't want to add percent to `SnapZoomOptions`, but any recommendation how I might go about that?

**Comment by davidfig** [comment]
snapZoom should have at least the scale options (percent makes less sense since it's an ongoing change). 

i don't have time right now to add it, but here's the formula you need to convert from scale to width: `const width = viewport.screenWidth / viewport.scale.x` Same for height except `screenHeight` and `scale.y`. (I think that's right, this is where I got it from: `this.xScale = parent.screenWidth / this.options.width`

Happy to take a PR adding this functionality if you have the time.

**Comment by jasonsturges** [comment]
@davidfig This is awesome, exactly what I needed to confirm.  Thanks!
