### ISSUE TITLE
Firefox scrolling too fast/sensitive

### ISSUE THREAD

**Issue by johnthagen** [davidfig/pixi-viewport#214]
We have a web application using `pixi-viewport`, but for users using Firefox, the zoom scrolling is much too fast compared to Chrome.

## How to reproduce

1. Open https://davidfig.github.io/pixi-viewport/ in Firefox (tested in 74.0.1, but observed with other versions).
2. Scroll in and out and notice how very fast/sensitive it is.
  - Compare this to Chrome (tested in 80.0.3987.149, but observed in others). Chrome's scrolling is much more controlled and natural.

**Comment by davidfig** [comment]
Is this for both wheel drag and wheel zoom? If so, can you experiment using `options.wheelScroll` (in `viewport.drag`) and `options.percent` in `viewport.wheel()` for a better value to default to for firefox? 

It would be great if there was a number we can just multiply by if firefox is detected. Once I have the multiple, I'll update it (unless you want to create a PR). Thanks!

**Comment by mcdenhoed** [comment]
Anecdotally, using Chrome on macOS 10.14 and scrolling my mouse one tick shows a `deltaMode` of 0 and `deltaY` of 4.

Meanwhile, using Firefox and scrolling one tick shows a `deltaMode` of 1 and a `deltaY` of 1 .

I noticed this line in the Wheel Plugin:

https://github.com/davidfig/pixi-viewport/blob/f5a0db698af9c35a9e3789d5d3440641c6e072dd/src/plugins/wheel.js#L89

Perhaps the issue here is simply that PIXI Viewport's fudge factor accounting for Line Scrolling is too sensitive? Based on my numbers above, changing that value to 4 should yield a more uniform experience (or better yet, maybe that should be a plugin option).

**Comment by johnthagen** [comment]
@davidfig If you are able to put up a preview / example with the above settings changed, I'd be happy to test it out for you.

**Comment by johnthagen** [comment]
@davidfig Would you mind reviewing #216?

**Comment by johnthagen** [comment]
Fixed in #216
