### ISSUE TITLE
Wheel behavior

### ISSUE THREAD

**Issue by LevinoMoises** [davidfig/pixi-viewport#23]
Hello Figatner, I noticed that the zoom calculation in the wheel event is calculated based in the current container scale value. 

For example, let's say that the wheel event was initialized with a 2% value. If you zoom in a single time, the scale value will go to 1.02. But if you zoom out after it, it won't go back to 1, it will go back to 0.9996. Is this the expected behavior?

**Comment by davidfig** [comment]
Since it's a percent, it likely won't return to a whole number because it uses multiplication of floating numbers. 

Alternatively, I could also add an options.scale that uses a fixed amount to change the scale with each scroll? For example, if you're at scale: 1.0 and options.scale = 0.25, then when you turn the wheel it will change to 1.25 or 0.75 based on the direction you choose. That would be result in fixed intervals and would be be relatively easy to implement. Let me know if it would be helpful and I'll add it to my list.

**Comment by LevinoMoises** [comment]
I don't think it's necessary. I was just curious if that was the expected behavior of this event. 

What would be helpful for me, was if the return event of the wheel contained the x and y of the mouse position when the event happened. This is not related at all with the issue, but would be helpful.

Thanks!

**Comment by davidfig** [comment]
That's already there if you listen for the 'wheel' event:

   viewport.on('wheel', callback) where the callback has parameters (wheel: {dx, dy, dz}, viewport)
