### ISSUE TITLE
Not compatible with pixi.js-legacy

### ISSUE THREAD

**Issue by dontwork** [davidfig/pixi-viewport#252]
We recently switched our codebase to pixi.js-legacy module and found pixi-viewport no longer worked. We forked it to change package.json and imports in the codebase and its all up and running but wasn't sure if there is a way for this to be better supported?

**Comment by davidfig** [comment]
I haven't tested it against pixi.js-legacy in a while. Do you know where it's broken? I remember when they first split it, I tried to support both.

**Comment by dontwork** [comment]
We had to change the 'pixi.js' imports to point to pixi-legacy and the same for the peer dep in package json. Not sure if that is the right thing to do but it got things working

**Comment by davidfig** [comment]
What problem are you having with viewport after the switch? I've worked on a project that used pixi-legacy recently, and I didn't have any problems.

**Comment by dontwork** [comment]
Can you detail how you got it working with no problems? the pixi-viewport code has imports looking for 'pixi.js' and has peerDependency on 'pixi.js' - we had to change these

**Comment by davidfig** [comment]
Hmm...I'm not sure how to fix this. Give a look at this pixi issue and see if it's any help: https://github.com/pixijs/pixi.js/issues/6155. 

It's possible to change architecture of the plugin so pixi is passed as an option, but I'm not sure that's much better since it'll still need to import pixi.js to ensure backwards compatibility with existing usages.
