### ISSUE TITLE
es5!

### ISSUE THREAD

**Issue by hassanshaikley** [davidfig/pixi-viewport#28]
I was going to create a fork that transpiles to es5 since that was giving me issues with create react app. I figured I might end up submitting a PR for it (since it seems fairly benign and simple) so I might as well ask first.

I tried using browserify to accomplish this but I was having issues converting it to es5 on the fly, in the index file. I was easily able to do it on the command line (to publish it to docs). But that isn't the entry point on npm.

So I will likely use babel for it.

I don't mind trying to do this in different ways. : :)

If this sounds useful I will submit a PR.

**Comment by davidfig** [comment]
Do you know how pixi.js handles es5? I know they use babel when they produce the pixi.min.js package. But not sure how they handle it for npm.

**Comment by hassanshaikley** [comment]
Looks like they use babel and something called pixify, especially made for PIXI!

https://www.npmjs.com/package/pixify

**Comment by hassanshaikley** [comment]
check this out!

https://github.com/hassanshaikley/pixi-viewport/commit/babd0072a5d6d465594eb2bc3ceb9435a16d8bbd

Let me know what you think. Now I am getting the same error with `pixi-ease`. I can submit a PR to both of them or create separate forks for myself. It's your call, David! Thank you for your incredible work.

**Comment by davidfig** [comment]
Does this mean we have to maintain two npm packages (similar to uglify-js / uglify-es)? 

pixi.js, is transpiling/babelifying its es6 source code when running pixify. They place the transpiled files into the /lib directory, which is what they export for npm. 

I wonder why they don't minify it during packaging and export that one file instead of the /lib directory since they're already using a map file.

It might make sense to come up with a similar solution. It's not like es6 runs faster than es5 (it's just much easier to code in). I'd love to deploy this in pixi-viewport, pixi-ease, and the rest of my npm'd projects, while maintaining the source code readability.

Thoughts?

**Comment by hassanshaikley** [comment]
In the fork I created I don't use pixify! I just use babel to transpile it. I have a hook that transpiles to es5 when you npm publish. Which is one of the things that PIXI does! 

yeah, I am not sure why they have it set up as separate files. I really didn't understand that bit. I suppose we could export it to one file if we wanted, but I don't imagine that makes much of a difference?

I can submit a PR with what I have got at the moment. This is mostly what I've got here:

https://github.com/hassanshaikley/pixi-viewport/commit/babd0072a5d6d465594eb2bc3ceb9435a16d8bbd

**Comment by davidfig** [comment]
It looks like pixi.js is following something close to this article: https://github.com/bookercodes/articles/blob/master/how-to-build-and-publish-es6-npm-modules-today-with-babel.md

It's similar to what you did. They transpile all the files and put it into a dist/ directory and then point npm to that directory. I'm happy to take a pull request if you want to try to finish the work. 

Will have to do same for pixi-ease since its a dependent.

If you don't have time, I'll try to take a crack at it this week.

**Comment by hassanshaikley** [comment]
Check it out! : )

https://github.com/davidfig/pixi-viewport/pull/29

Let me know if it is missing anything!

**Comment by davidfig** [comment]
Nice! The pixi-more branch now supports es5. I'm hoping to push this to master soon after more testing. I also updated pixi-ease, so it should be a full es5 solution.

**Comment by hassanshaikley** [comment]
Yay, thanks David. PS I would happily contribute in more ways, if you have any smaller things you want done let me know. I have been meaning to test the `pixi-more` branch and give you feedback. I hope to get to that soon!

Thanks again for your awesome work!

**Comment by davidfig** [comment]
@hassanshaikley, since I added es5 support to pixi-viewport, do you mind deprecating pixi-viewport-es5 (npm deprecate pixi-viewport-es5 <message>)? 

It caused some confusion when I was providing support when someone thought they were using pixi-viewport but accidentally installed pixi-viewport-es5.

Thanks!

**Comment by hassanshaikley** [comment]
My bad, David! I will get to this right now. : )

**Comment by davidfig** [comment]
Awesome. Thanks!
