### ISSUE TITLE
Including @pixi/ instead of pixi.js

### ISSUE THREAD

**Issue by davidfig** [davidfig/pixi-viewport#314]
@SukantPal 

I'm running into some issues with including portions of @pixi/ instead of the whole library, particularly when using it standalone. Is there a reason you made this change?

**Comment by SukantPal** [comment]
PixiJS packages are supposed to use scoped @pixi/ packages so that you don't lock-in end users from using a particular bundle. What issues are you facing?

**Comment by DanBoSlice** [comment]
I think the problem is, that the `@pixi/*` packages are added as dev dependencies and therefore won't automatically be installed when adding `pixi-viewport` to a project.

For example, I get the error `Property 'addChild' does not exist on type 'Viewport'.` and have to install the `@pixi/*` packages manually.

**Comment by davidfig** [comment]
@Sukant is there a way to make this work? Otherwise we should revert to including the entire package. With modern tree shaking, I don't think this is as big a concern.

**Comment by SukantPal** [comment]
When you install `pixi.js` all those packages should be installed. What version of PixiJS are you using?

**Comment by DanBoSlice** [comment]
Working with pixi.js version 5.3.9 and pixi-viewport version 4.31.0.

**Comment by SukantPal** [comment]
pixi-viewport only supports PixiJS 6 and above now. The peer-dependency explicitly says ^6.0.0

**Comment by DanBoSlice** [comment]
Hmm, that's unfortunate. I had some problems getting Pixi v6 to run with Angular. But that's not an issue with pixi-viewport then.

**Comment by SukantPal** [comment]
PixiJS 6 now has per-package typings that's why. I don't think there have been changes much change in pixi-viewport since before 4.3.0 apart from using scoped PixiJS packages.

**Comment by SukantPal** [comment]
You should try PixiJS 5.4.0-RC - it also has per-package typings so that _might_ fix it.

**Comment by RSamaium** [comment]
> pixi-viewport only supports PixiJS 6 and above now. The peer-dependency explicitly says ^6.0.0

It's a good thing that it supports version 6 but it should have been a major version for PIXI Viewport (version 5 and not 4.30)

Because it is a problem with the following configuration (`package.json`):

```json
"dependencies": {
    "pixi-viewport": "^4.15.0",
    "pixi.js": "^5.3.10"
}
```

In my case, since 4.30 is considered a minor version, it will take this last version and look for PIXI v6 (while I am on Pixi v5)
I end up with a mix of v5 and v6 dependencies. I end up with bugs because the game will load v6 dependencies

So, to solve the problem, I had to fix the version in `package.json`

```json
"dependencies": {
    "pixi-viewport": "4.15.0",
    "pixi.js": "^5.3.10"
}
```

When you say it like that, it's simple but I had a hard time finding the problem because I focused on PIXI which was using version 6 when I never asked it...
