### ISSUE TITLE
[Question] Any easy to grasp explanation of how local/global/world/screen positions interact?

### ISSUE THREAD

**Issue by datrinh** [davidfig/pixi-viewport#369]
Hi, I very recently started using pixi, and pixi-viewport provides a great foundation.
My biggest recurring issue is the positioning of elements when interacting with the canvas. Everything works great if I don't zoom or pan around. After zooming, the elements position are off, and I usually fix it by randomly combining `toLocal`, `toGlobal`, `toWorld`, `toScreen` and `toGlobalPosition`. I'd like to understand how and why things are working or not, though.

**Comment by davidfig** [comment]
Viewport has its own coordinate system. When adding children to viewport, think of their coordinates as the world coordinates. The viewport is a view into those world coordinates. When you zoom or pan, you're changing the location and size of that window. You'll want to convert pointer events into the world coordinates to work with them (use `viewport.toWorld`). Otherwise, you should try to stay in the world coordinates and let viewport handle everything else.

**Comment by datrinh** [comment]
@davidfig That was quite easy to grasp thanks :) May I suggest such a text within the documentation?

**Comment by jasonsturges** [comment]
@datrinh Found myself in a similar situation regarding the coordinate system.

Not sure if it helps, but I attempted to isolate a test harness I created from an early app into a CodeSandbox:
https://codesandbox.io/s/pixi-viewport-coordinate-system-xzcdh

In a 1000x1000 world (white rectangle), the circle tracks the pointer from global to world coordinate system:

<img width="1056" alt="pixi-viewport-coordinate-system" src="https://user-images.githubusercontent.com/1213591/153701614-5338ffde-12e9-4da0-89f1-48c66327fbf7.png">

If that doesn't represent your needs, perhaps it serves as a starting point to fork and alter to test different scenarios.

Personally I think my confusion stems from camera systems in a stationary world versus the world itself moving.  It seems nebulous at first; however, becomes logical over time.
