### ISSUE TITLE
Click event fires after dragging

### ISSUE THREAD

**Issue by qwertysam** [davidfig/pixi-viewport#37]

**Comment by davidfig** [comment]
Fixed. I put back to the 'clicked' event since PIXI's 'click' event only fired on mouse (they use 'pointertap' for both), and it doesn't cancel after movement. Thanks!

**Comment by xAvarice** [comment]
Drag event fires non-stop until you click again... related to this?

**Comment by davidfig** [comment]
I'm not seeing this. Can you provide code to replicate?

**Comment by xAvarice** [comment]
MAP.VIEWPORT.on('moved', () => { console.log('moved'); });

My implementation is incredibly light on pixi-viewport dependence so unless it is related to version or screen size or the parent container being set by flexbox it isn't my code.

I did notice that when I scroll on the map my logo at the top was getting selected so perhaps it is due to flexbox layout.

**Comment by davidfig** [comment]
There's newer versions of pixi-viewport, but I haven't changed anything that should be causing this. Can you explain the scenario. 'moved' continues to fire even after letting go of the mouse button? Are you using the decelerate() plugin (since it causes a 'moved' event as well)?

**Comment by xAvarice** [comment]
Yes, sir. I am using the decelerate - that explains it. Am I stupid or is that not intuitive? I realise you do not have control over plugins completely and must use the common hooks that exist.

Thank you for your great work, it is helping me a lot. Do you have donations set up anywhere?

**Comment by davidfig** [comment]
Glad we figured it out. I do control the plugins since I wrote them all :) I guess it's not super clear, but moved fires whenever the viewport is moved by a plugin, including the decelerate (since the viewport is still moving). I'll add a note the documentation.

No donation set up yet. One of these days... Good luck!
