### ISSUE TITLE
Passive event listeners for "wheel"

### ISSUE THREAD

**Issue by macropp** [davidfig/pixi-viewport#76]
Should we consider making `wheel` event listeners passive? I don't know if this could have any bad influence on performance since we want the zooming to be smooth/blocking. Chrome is complaining about this: https://www.chromestatus.com/feature/5745543795965952

Any ideas?

**Comment by davidfig** [comment]
I'm not sure. For full screen viewports, I usually set passive=true to avoid the chrome warnings (and since there's nothing underneath to scroll). For partial-screen viewports where the user may scroll the underlying html, I set passive to false, since I call preventDefault to stop the wheel from scrolling when zooming the viewport.

My thought is to add passive: true to the wheel event unless (the yet-to-be-added) options.passiveMouse=false is set on viewport.

Thoughts?

**Comment by macropp** [comment]
I think it'd be great to give the user ability to configure that. In my usecase all viewports are fullscreen, so it probably makes sense for me to put it passive.

**Comment by davidfig** [comment]
I added options.passiveWheel in 4.7.0. It's defaulted to true since I think that's the common use.
