### ISSUE TITLE
Double click issue

### ISSUE THREAD

**Issue by hpretel** [davidfig/pixi-viewport#99]
After two o more clicks in the same point of the viewport, i can't drag the viewport freely and the pointer looks locked.
The issue appears too in https://davidfig.github.io/pixi-viewport/

**Comment by davidfig** [comment]
Hmm . . . I've seen it happen sometimes when I click like crazy. Is it common? It may be related to dragging (the cursor turns into a not permitted sign). How are you replicating it?

**Comment by hpretel** [comment]
I just double click, move the mouse and I can't do the drag in the viewport (the cursor turns into a not permitted sign). It happens always in that condition.

**Comment by davidfig** [comment]
What browser/OS are you using?

**Comment by hpretel** [comment]
OS: Windows 8.1
Browser: Google Chrome

**Comment by hpretel** [comment]
I use a laptop touchpad

**Comment by davidfig** [comment]
I think I found it:

1. double click on the viewport and then release mouse button
2. try to drag the viewport (nothing happens after an initial jerk)
3. single click on the viewport and it returns to normal

Is that your experience?

**Comment by hpretel** [comment]
Yes. It's true. After a single click it returns to normal.

**Comment by davidfig** [comment]
Okay. I think I figured it out. If you double click on the screen, then the browser is selecting elements (e.g., text nodes) that are on the browser page. When you then click and drag, it ends up dragging the selected element instead of the viewport. You can see this when after you click for the third time, you drag the cursor over to the debug pane and drop it in the console. It'll likely be a piece of text.

I played around with a few workarounds to add to pixi-viewport but couldn't find anything that consistently worked. 

An easy fix is to remove or set user-select: none to any draggable elements on the HTML page. Then when you double click there will be nothing selectable.

There's probably a better solution (I played with preventDefault), but I couldn't get it to work properly. Let me know if you come up with a better solution.

**Comment by hpretel** [comment]
Okay. I understand. Thanks :)
